title: 'jas9reet.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://jas9reet.github.io"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/jas9reet">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: jas9reet/jas9reet.github.io
